menu:
  主页: /
  归档: /archives

logo: CG

more:
  友情链接: /links.html
  Github: https://github.com/XXX/
  微博: http://weibo.com/XXX
  知乎: https://www.zhihu.com/people/XXX
  rss: /rss2.xml
  关于我: /

about:
  title: Chonggao Liu
  link: https://github.com/gaoryrt/hexo-theme-pln

#disqus_shortname: yourdisqustoken
duoshuo_shortname: liuchonggao

excerpt_num: 120

footer_info: © chonggao.liu 2015-2016